### ISSUE TITLE
make pipe-able command line scripts

### ISSUE THREAD

**Issue by jonasjonker** [jonasjonker/Integrated-Bioinformatics-Project#16]
We should generate some scripts for our analysis pipeline. 

You can parse commanline argument with something like this:
```R
options(echo=TRUE) # To see commands in output file
args <- commandArgs(trailingOnly = TRUE)
x <- args[1]
y <- args[y]
```

**Tasks:**

- [x] **create_signac_obj.R**
   Should work from the command line with the following command:
       `Rscript create_signac_obj.R feature_matrix.h5 feature_summary.csv signac_obj.rds`
- [x] **generate_signac_obj_report.R**
Should work from the command line with the following command:
       `Rscript generate_signac_obj_report.R signac_obj.rds`
- [x] **create_mofa2_obj.R**
Should work from the command line with the following command:
       `Rscript generate_signac_obj_report.R signac_obj.rds report.html`
- [x] **generate_mofa2_obj_report.R**
Should work from the command line with the following command:
       `Rscript generate_mofa2_obj_report.R signac_obj.rds untrained_mofa2_obj.rds`
- [x] **train_mofa2_obj.R**
Should work from the command line with the following command:
       `Rscript train_mofa2_obj.R untrained_mofa2_obj.rds trained_mofa2_obj.rds`
